import type { QuizHistoryType } from '../../composables/useQuizHistory'

export const QUIZ_TYPE_LABEL: Record<QuizHistoryType, string> = {
  'noun-gender': 'Noun gender',
  'noun-translation': 'Noun translation',
  adjective: 'Adjective',
  'verb-translation': 'Verb translation',
  'verb-conjugation': 'Verb conjugation',
  'verb-stammformen': 'Verb · principal parts',
  'verb-case-government': 'Verb · case government',
  'prep-case': 'Preposition · case',
  'prep-article': 'Preposition · article',
  'prep-two-way': 'Preposition · two-way',
  'prep-collocations': 'Preposition · fixed',
  'dac-formation': 'Da-compounds · formation',
  'dac-match': 'Da-compounds · matching',
  'dac-substitution': 'Da-compounds · gap-fill',
  'dac-neighbors': 'Da-compounds · near neighbors',
  'dac-case': 'Da-compounds · case',
  'dac-pronoun-case': 'Da-compounds · pronoun case',
  'dac-article': 'Da-compounds · article fill',
  'dac-transform': 'Da-compounds · thing or person',
  'dac-wo-question': 'Da-compounds · wo-questions',
  'dac-dialogue': 'Da-compounds · dialogue',
  'dac-korrelat': 'Da-compounds · Korrelat',
  'dac-paraphrase': 'Da-compounds · paraphrase',
  'dac-contrast': 'Da-compounds · meaning contrast',
  'dac-sentence': 'Da-compounds · sentence (AI)',
  'dac-assembly': 'Da-compounds · assembly',
  'dac-answer': 'Da-compounds · answer (AI)',
  'dac-homograph': 'Da-compounds · homographs',
  'dac-register': 'Da-compounds · register',
  'dac-relative': 'Da-compounds · relative clauses',
  'dw-hinher': 'Direction words · hin or her',
  'dw-compound': 'Direction words · compounds',
  'dw-question': 'Direction words · wo/wohin/woher',
  'dw-register': 'Direction words · register',
  'dw-assembly': 'Direction words · assembly',
  'dw-sentence': 'Direction words · sentence (AI)',
  'dw-answer': 'Direction words · answer (AI)',
  'dw-lexical': 'Direction words · lexicalized verbs',
  'dw-idiom': 'Direction words · idioms',
  'prep-sentence': 'Preposition · sentence (AI)',
  'prep-remedial': 'Preposition · remedial',
  'verb-sentence': 'Verb · sentence (AI)',
  'verb-remedial': 'Verb · remedial',
  'decl-table': 'Declension · table',
  'decl-article': 'Declension · article',
  'decl-adjective': 'Declension · adj. ending',
  'decl-pronoun': 'Declension · pronouns',
  'decl-case-recognition': 'Declension · case ID',
  'decl-article-ai': 'Declension · article (AI)',
  'konjunktiv-rewrite': 'Konjunktiv I — indirect speech',
  'passiv-transform': 'Passiv transformation',
  'writing-grade': 'Writing · graded essay',
  'simulator-c1': 'Goethe C1 · Mock exam',
  'sprechen-teil1': 'Sprechen · Teil 1 Vortrag',
  'schreiben-teil1': 'Schreiben · Teil 1 Forumsbeitrag',
  'schreiben-teil2': 'Schreiben · Teil 2 Nachricht',
  'sprechen-teil2': 'Sprechen · Teil 2 discussion',
  'sprechen-drill': 'Sprechen · Korrekturdrill',
  'sentence-packed': 'Sentence · packed (AI)',
  'dat-case': 'Dative · case pick',
  'dat-form': 'Dative · object form',
  'dat-trap': 'Dative · trap cards',
  'dat-subject': 'Dative · who is subject',
  'dat-experiencer': 'Dative · experiencer production',
  'dat-twin': 'Dative · twin pairs',
  'dat-ditrans': 'Dative · which object',
  'dat-object-order': 'Dative · object order',
  'dat-adjective': 'Dative · adjectives',
  'dat-free': 'Dative · free dative',
  'dat-sentence': 'Dative · sentence (AI)',
  'dat-passive': 'Dative · passive',
  'dat-reflexive': 'Dative · reflexive',
  'relativ-pronomen': 'Relative pronouns',
  'ndekl-form': 'Weak nouns',
  'wortschatz-lernen': 'Wortschatz · Lernen',
  'wortschatz-wiederholen': 'Wortschatz · Wiederholen'
}

export const QUIZ_TYPE_DE: Record<QuizHistoryType, string> = {
  'noun-gender': 'Genus',
  'noun-translation': 'Substantive',
  adjective: 'Adjektive',
  'verb-translation': 'Übersetzen',
  'verb-conjugation': 'Konjugation',
  'verb-stammformen': 'Verb · Stammformen',
  'verb-case-government': 'Verb · Rektion',
  'prep-case': 'Präposition · Kasus',
  'prep-article': 'Präposition · Artikel',
  'prep-two-way': 'Präposition · Wechsel',
  'prep-collocations': 'Feste Präpositionen',
  'dac-formation': 'Da-Compounds · Bildung',
  'dac-match': 'Da-Compounds · Zuordnung',
  'dac-substitution': 'Da-Compounds · Lückentext',
  'dac-neighbors': 'Da-Compounds · Verwechslung',
  'dac-case': 'Da-Compounds · Kasus',
  'dac-pronoun-case': 'Da-Compounds · Pronomen-Kasus',
  'dac-article': 'Da-Compounds · Artikel',
  'dac-transform': 'Da-Compounds · Sache oder Person',
  'dac-wo-question': 'Da-Compounds · W-Fragen',
  'dac-dialogue': 'Da-Compounds · Dialog',
  'dac-korrelat': 'Da-Compounds · Korrelat',
  'dac-paraphrase': 'Da-Compounds · Umformung',
  'dac-contrast': 'Da-Compounds · Bedeutungskontrast',
  'dac-sentence': 'Da-Compounds · Satz (KI)',
  'dac-assembly': 'Da-Compounds · Satzbau',
  'dac-answer': 'Da-Compounds · Antworten (KI)',
  'dac-homograph': 'Da-Compounds · Doppelgänger',
  'dac-register': 'Da-Compounds · Register',
  'dac-relative': 'Da-Compounds · Relativsätze',
  'dw-hinher': 'Hin & Her · Grundregel',
  'dw-compound': 'Hin & Her · Zusammensetzungen',
  'dw-question': 'Hin & Her · Fragewörter',
  'dw-register': 'Hin & Her · Kurzformen',
  'dw-assembly': 'Hin & Her · Satzbau',
  'dw-sentence': 'Hin & Her · Satz (KI)',
  'dw-answer': 'Hin & Her · Antworten (KI)',
  'dw-lexical': 'Hin & Her · Verblasste Richtung',
  'dw-idiom': 'Hin & Her · Redewendungen',
  'prep-sentence': 'Präposition · Satz (KI)',
  'prep-remedial': 'Präposition · Schwachstellen',
  'verb-sentence': 'Verb · Satz (KI)',
  'verb-remedial': 'Verb · Schwachstellen',
  'decl-table': 'Deklination · Tabelle',
  'decl-article': 'Deklination · Artikel',
  'decl-adjective': 'Deklination · Endung',
  'decl-pronoun': 'Deklination · Pronomen',
  'decl-case-recognition': 'Deklination · Kasus erkennen',
  'decl-article-ai': 'Deklination · Artikel (KI)',
  'konjunktiv-rewrite': 'Konjunktiv I · Indirekte Rede',
  'passiv-transform': 'Passiv · Transformation',
  'writing-grade': 'Schreiben · benoteter Aufsatz',
  'simulator-c1': 'Goethe C1 · Prüfungssimulation',
  'sprechen-teil1': 'Sprechen · Teil 1 Vortrag',
  'schreiben-teil1': 'Schreiben · Teil 1 Forumsbeitrag',
  'schreiben-teil2': 'Schreiben · Teil 2 Nachricht',
  'sprechen-teil2': 'Sprechen · Teil 2 Diskussion',
  'sprechen-drill': 'Sprechen · Korrekturdrill',
  'sentence-packed': 'Satz · Gepackt (KI)',
  'dat-case': 'Dativ · Dativ oder Akkusativ',
  'dat-form': 'Dativ · Dativobjekt',
  'dat-trap': 'Dativ · Fallen-Karten',
  'dat-subject': 'Dativ · Wer ist Subjekt',
  'dat-experiencer': 'Dativ · Produktion',
  'dat-twin': 'Dativ · Zwillingspaare',
  'dat-ditrans': 'Dativ · Welches Objekt',
  'dat-object-order': 'Dativ · Objektfolge',
  'dat-adjective': 'Dativ · Adjektive',
  'dat-free': 'Dativ · Freier Dativ',
  'dat-sentence': 'Dativ · Satz (KI)',
  'dat-passive': 'Dativ · Passiv',
  'dat-reflexive': 'Dativ · Reflexiv',
  'relativ-pronomen': 'Relativpronomen',
  'ndekl-form': 'N-Deklination',
  'wortschatz-lernen': 'Wortschatz · Lernen',
  'wortschatz-wiederholen': 'Wortschatz · Wiederholen'
}

export const QUIZ_TYPES_ORDER: QuizHistoryType[] = [
  'noun-gender',
  'noun-translation',
  'adjective',
  'verb-translation',
  'verb-conjugation',
  'verb-stammformen',
  'verb-case-government',
  'verb-sentence',
  'verb-remedial',
  'prep-case',
  'prep-article',
  'prep-two-way',
  'prep-collocations',
  'dac-formation',
  'dac-match',
  'dac-substitution',
  'dac-neighbors',
  'dac-case',
  'dac-pronoun-case',
  'dac-article',
  'dac-transform',
  'dac-wo-question',
  'dac-dialogue',
  'dac-korrelat',
  'dac-paraphrase',
  'dac-contrast',
  'dac-sentence',
  'dac-assembly',
  'dac-answer',
  'dac-homograph',
  'dac-register',
  'dac-relative',
  'dw-hinher',
  'dw-compound',
  'dw-question',
  'dw-register',
  'dw-assembly',
  'dw-sentence',
  'dw-answer',
  'dw-lexical',
  'dw-idiom',
  'prep-sentence',
  'prep-remedial',
  'sentence-packed',
  'decl-table',
  'decl-article',
  'decl-adjective',
  'decl-pronoun',
  'decl-case-recognition',
  'decl-article-ai',
  'konjunktiv-rewrite',
  'passiv-transform',
  'writing-grade',
  'simulator-c1',
  'sprechen-teil1',
  'schreiben-teil1',
  'schreiben-teil2',
  'sprechen-teil2',
  'sprechen-drill',
  'dat-case',
  'dat-form',
  'dat-trap',
  'dat-subject',
  'dat-experiencer',
  'dat-twin',
  'dat-ditrans',
  'dat-object-order',
  'dat-adjective',
  'dat-free',
  'dat-sentence',
  'dat-passive',
  'dat-reflexive',
  'relativ-pronomen',
  'ndekl-form',
  'wortschatz-lernen',
  'wortschatz-wiederholen'
]
