import type { QuizHistoryType } from '../../composables/useQuizHistory'

export const QUIZ_TYPE_LABEL: Record<QuizHistoryType, string> = {
  'noun-gender': 'Noun gender',
  'noun-translation': 'Noun translation',
  adjective: 'Adjective',
  'verb-translation': 'Verb translation',
  'verb-conjugation': 'Verb conjugation',
  'verb-stammformen': 'Verb · principal parts',
  'verb-case-government': 'Verb · case government',
  'prep-case': 'Preposition · case',
  'prep-article': 'Preposition · article',
  'prep-two-way': 'Preposition · two-way',
  'prep-collocations': 'Preposition · fixed',
  'prep-sentence': 'Preposition · sentence (AI)',
  'prep-remedial': 'Preposition · remedial',
  'verb-sentence': 'Verb · sentence (AI)',
  'verb-remedial': 'Verb · remedial',
  'decl-table': 'Declension · table',
  'decl-article': 'Declension · article',
  'decl-adjective': 'Declension · adj. ending',
  'decl-pronoun': 'Declension · pronouns',
  'decl-case-recognition': 'Declension · case ID',
  'decl-article-ai': 'Declension · article (AI)',
  'konjunktiv-rewrite': 'Konjunktiv I — indirect speech',
  'passiv-transform': 'Passiv transformation',
  'writing-grade': 'Writing · graded essay',
  'simulator-c1': 'Goethe C1 · Mock exam'
}

export const QUIZ_TYPE_DE: Record<QuizHistoryType, string> = {
  'noun-gender': 'Genus',
  'noun-translation': 'Substantive',
  adjective: 'Adjektive',
  'verb-translation': 'Übersetzen',
  'verb-conjugation': 'Konjugation',
  'verb-stammformen': 'Verb · Stammformen',
  'verb-case-government': 'Verb · Rektion',
  'prep-case': 'Präposition · Kasus',
  'prep-article': 'Präposition · Artikel',
  'prep-two-way': 'Präposition · Wechsel',
  'prep-collocations': 'Feste Präpositionen',
  'prep-sentence': 'Präposition · Satz (KI)',
  'prep-remedial': 'Präposition · Schwachstellen',
  'verb-sentence': 'Verb · Satz (KI)',
  'verb-remedial': 'Verb · Schwachstellen',
  'decl-table': 'Deklination · Tabelle',
  'decl-article': 'Deklination · Artikel',
  'decl-adjective': 'Deklination · Endung',
  'decl-pronoun': 'Deklination · Pronomen',
  'decl-case-recognition': 'Deklination · Kasus erkennen',
  'decl-article-ai': 'Deklination · Artikel (KI)',
  'konjunktiv-rewrite': 'Konjunktiv I · Indirekte Rede',
  'passiv-transform': 'Passiv · Transformation',
  'writing-grade': 'Schreiben · benoteter Aufsatz',
  'simulator-c1': 'Goethe C1 · Prüfungssimulation'
}

export const QUIZ_TYPES_ORDER: QuizHistoryType[] = [
  'noun-gender',
  'noun-translation',
  'adjective',
  'verb-translation',
  'verb-conjugation',
  'verb-stammformen',
  'verb-case-government',
  'verb-sentence',
  'verb-remedial',
  'prep-case',
  'prep-article',
  'prep-two-way',
  'prep-collocations',
  'prep-sentence',
  'prep-remedial',
  'decl-table',
  'decl-article',
  'decl-adjective',
  'decl-pronoun',
  'decl-case-recognition',
  'decl-article-ai',
  'konjunktiv-rewrite',
  'passiv-transform',
  'writing-grade',
  'simulator-c1'
]
