import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router'

const routes: RouteRecordRaw[] = [
  { path: '/', name: 'home', component: () => import('./modules/home/Home.vue') },
  { path: '/history', name: 'history', component: () => import('./modules/history/HistoryPage.vue') },
  { path: '/version', name: 'version', component: () => import('./modules/version/VersionPage.vue') },
  { path: '/settings', name: 'settings', component: () => import('./modules/settings/Settings.vue') },
  { path: '/nouns', name: 'nouns', component: () => import('./modules/nouns/NounsHome.vue') },
  { path: '/nouns/manage', name: 'nouns-manage', component: () => import('./modules/nouns/ManageNouns.vue') },
  { path: '/nouns/quiz', name: 'nouns-quiz', component: () => import('./modules/nouns/QuizSetup.vue') },
  { path: '/nouns/quiz/run', name: 'nouns-quiz-run', component: () => import('./modules/nouns/QuizRunner.vue') },
  { path: '/adjectives', name: 'adjectives', component: () => import('./modules/adjectives/AdjectivesHome.vue') },
  { path: '/adjectives/manage', name: 'adjectives-manage', component: () => import('./modules/adjectives/ManageAdjectives.vue') },
  { path: '/adjectives/quiz', name: 'adjectives-quiz', component: () => import('./modules/adjectives/QuizSetup.vue') },
  { path: '/adjectives/quiz/run', name: 'adjectives-quiz-run', component: () => import('./modules/adjectives/QuizRunner.vue') },
  { path: '/verbs', name: 'verbs', component: () => import('./modules/verbs/VerbsHome.vue') },
  { path: '/verbs/list', name: 'verbs-list', component: () => import('./modules/verbs/ListVerbs.vue') },
  { path: '/verbs/translation', name: 'verbs-translation', component: () => import('./modules/verbs/TranslationQuizSetup.vue') },
  { path: '/verbs/translation/run', name: 'verbs-translation-run', component: () => import('./modules/verbs/TranslationQuizRunner.vue') },
  { path: '/verbs/translation/result', name: 'verbs-translation-result', component: () => import('./modules/verbs/TranslationQuizResult.vue') },
  { path: '/verbs/conjugation', name: 'verbs-conjugation', component: () => import('./modules/verbs/ConjugationQuizSetup.vue') },
  { path: '/verbs/conjugation/run', name: 'verbs-conjugation-run', component: () => import('./modules/verbs/ConjugationQuizRunner.vue') },
  { path: '/verbs/cheatsheet', name: 'verbs-cheatsheet', component: () => import('./modules/verbs/CheatSheet.vue') },
  { path: '/prepositions', name: 'prepositions', component: () => import('./modules/prepositions/PrepositionsHome.vue') },
  { path: '/prepositions/list', name: 'prepositions-list', component: () => import('./modules/prepositions/ListPrepositions.vue') },
  { path: '/prepositions/case-quiz', name: 'prepositions-case', component: () => import('./modules/prepositions/CaseQuizSetup.vue') },
  { path: '/prepositions/case-quiz/run', name: 'prepositions-case-run', component: () => import('./modules/prepositions/CaseQuizRunner.vue') },
  { path: '/prepositions/case-quiz/result', name: 'prepositions-case-result', component: () => import('./modules/prepositions/CaseQuizResult.vue') },
  { path: '/prepositions/article-quiz', name: 'prepositions-article', component: () => import('./modules/prepositions/ArticleQuizSetup.vue') },
  { path: '/prepositions/article-quiz/run', name: 'prepositions-article-run', component: () => import('./modules/prepositions/ArticleQuizRunner.vue') },
  { path: '/prepositions/two-way-quiz', name: 'prepositions-twoway', component: () => import('./modules/prepositions/TwoWayQuizSetup.vue') },
  { path: '/prepositions/two-way-quiz/run', name: 'prepositions-twoway-run', component: () => import('./modules/prepositions/TwoWayQuizRunner.vue') },
  { path: '/declension', name: 'declension', component: () => import('./modules/declension/DeclensionHome.vue') },
  { path: '/declension/tables', name: 'declension-tables', component: () => import('./modules/declension/TablesReference.vue') },
  { path: '/declension/table-quiz', name: 'declension-table', component: () => import('./modules/declension/TableQuizSetup.vue') },
  { path: '/declension/table-quiz/run', name: 'declension-table-run', component: () => import('./modules/declension/TableQuizRunner.vue') },
  { path: '/declension/table-quiz/result', name: 'declension-table-result', component: () => import('./modules/declension/TableQuizResult.vue') },
  { path: '/declension/article-quiz', name: 'declension-article', component: () => import('./modules/declension/ArticleQuizSetup.vue') },
  { path: '/declension/article-quiz/run', name: 'declension-article-run', component: () => import('./modules/declension/ArticleQuizRunner.vue') },
  { path: '/declension/article-quiz/ai-run', name: 'declension-article-ai-run', component: () => import('./modules/declension/ArticleAIQuizRunner.vue') },
  { path: '/declension/adj-quiz', name: 'declension-adj', component: () => import('./modules/declension/AdjectiveQuizSetup.vue') },
  { path: '/declension/adj-quiz/run', name: 'declension-adj-run', component: () => import('./modules/declension/AdjectiveQuizRunner.vue') },
  { path: '/declension/pronoun-quiz', name: 'declension-pronoun', component: () => import('./modules/declension/PronounQuizSetup.vue') },
  { path: '/declension/pronoun-quiz/run', name: 'declension-pronoun-run', component: () => import('./modules/declension/PronounQuizRunner.vue') },
  { path: '/declension/pronoun-quiz/result', name: 'declension-pronoun-result', component: () => import('./modules/declension/PronounQuizResult.vue') },
  { path: '/declension/case-recognition', name: 'declension-cr', component: () => import('./modules/declension/CaseRecognitionSetup.vue') },
  { path: '/declension/case-recognition/run', name: 'declension-cr-run', component: () => import('./modules/declension/CaseRecognitionRunner.vue') },
  { path: '/konjunktiv', name: 'konjunktiv', component: () => import('./modules/konjunktiv/KonjunktivHome.vue') },
  { path: '/konjunktiv/quiz', name: 'konjunktiv-quiz', component: () => import('./modules/konjunktiv/QuizSetup.vue') },
  { path: '/konjunktiv/quiz/run', name: 'konjunktiv-quiz-run', component: () => import('./modules/konjunktiv/QuizRunner.vue') },
  { path: '/konjunktiv/quiz/result', name: 'konjunktiv-quiz-result', component: () => import('./modules/konjunktiv/QuizResult.vue') },
  { path: '/passiv', name: 'passiv', component: () => import('./modules/passiv/PassivHome.vue') },
  { path: '/passiv/quiz', name: 'passiv-quiz', component: () => import('./modules/passiv/QuizSetup.vue') },
  { path: '/passiv/quiz/run', name: 'passiv-quiz-run', component: () => import('./modules/passiv/QuizRunner.vue') },
  { path: '/passiv/quiz/result', name: 'passiv-quiz-result', component: () => import('./modules/passiv/QuizResult.vue') },
  { path: '/writing', name: 'writing', component: () => import('./modules/writing/WritingHome.vue') },
  { path: '/writing/task/:taskType', name: 'writing-task', component: () => import('./modules/writing/PromptDetail.vue') },
  { path: '/writing/prompt/:promptId', name: 'writing-prompt', component: () => import('./modules/writing/PromptDetail.vue') },
  { path: '/writing/prompt/:promptId/draft/new', name: 'writing-draft-new', component: () => import('./modules/writing/EditorSurface.vue') },
  { path: '/writing/prompt/:promptId/draft/:draftId', name: 'writing-draft', component: () => import('./modules/writing/EditorSurface.vue') },
  { path: '/writing/compare/:draftA/:draftB', name: 'writing-compare', component: () => import('./modules/writing/DraftCompare.vue') },
  { path: '/simulator', name: 'simulator-c1', component: () => import('./modules/simulator-c1/SimulatorHome.vue') },
  { path: '/simulator/run/:sessionId', name: 'simulator-run', component: () => import('./modules/simulator-c1/SimulatorRun.vue') },
  { path: '/simulator/result/:sessionId', name: 'simulator-result', component: () => import('./modules/simulator-c1/SimulatorResult.vue') }
]

export const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes
})
